#!/usr/bin/env bash
# ops/scripts/gcp-setup.sh
#
# One-time bootstrap for a new GCP project before Terraform.
# Safe to re-run — every step checks if work is already done.
#
# Prerequisites:
#   gcloud CLI authenticated (gcloud auth login)
#   firebase CLI installed  (npm install -g firebase-tools)
#   PROJECT_ID env var set, or passed as first argument
#
# Usage:
#   PROJECT_ID=reflective-staging bash ops/scripts/gcp-setup.sh
#   bash ops/scripts/gcp-setup.sh reflective-staging

set -euo pipefail

# ── Resolve project ID ─────────────────────────────────────────────────────────
PROJECT_ID="${1:-${PROJECT_ID:-}}"
if [[ -z "${PROJECT_ID}" ]]; then
  echo "ERROR: PROJECT_ID is not set."
  echo "Usage: PROJECT_ID=reflective-staging bash ops/scripts/gcp-setup.sh"
  exit 1
fi

TFSTATE_BUCKET="${PROJECT_ID}-tfstate"
TF_BACKEND_FILE="ops/infra/terraform/backend.tf"

echo "==> GCP project bootstrap"
echo "    Project:       ${PROJECT_ID}"
echo "    TF state bucket: gs://${TFSTATE_BUCKET}"
echo ""

# ── 1. Set default project ─────────────────────────────────────────────────────
echo "==> [1/6] Setting gcloud default project..."
gcloud config set project "${PROJECT_ID}"

# ── 2. Enable billing ──────────────────────────────────────────────────────────
echo "==> [2/6] Checking billing..."
BILLING_ACCOUNT=$(gcloud beta billing projects describe "${PROJECT_ID}" \
  --format="value(billingAccountName)" 2>/dev/null || true)

if [[ -z "${BILLING_ACCOUNT}" || "${BILLING_ACCOUNT}" == "None" ]]; then
  echo ""
  gcloud beta billing accounts list
  echo ""
  read -rp "Enter billing account ID from the list above (e.g. 012345-ABCDEF-012345): " BILLING_ACCOUNT_ID
  gcloud beta billing projects link "${PROJECT_ID}" \
    --billing-account="${BILLING_ACCOUNT_ID}"
  echo "    Billing linked."
else
  echo "    Billing already linked: ${BILLING_ACCOUNT}"
fi

# ── 3. Enable required APIs ────────────────────────────────────────────────────
echo "==> [3/6] Enabling required GCP APIs..."

REQUIRED_APIS=(
  "firestore.googleapis.com"
  "spanner.googleapis.com"
  "storage.googleapis.com"
  "pubsub.googleapis.com"
  "bigquery.googleapis.com"
  "aiplatform.googleapis.com"
  "redis.googleapis.com"
  "secretmanager.googleapis.com"
  "run.googleapis.com"
  "cloudbuild.googleapis.com"
  "artifactregistry.googleapis.com"
  "firebase.googleapis.com"
  "identitytoolkit.googleapis.com"
  "cloudresourcemanager.googleapis.com"
  "servicenetworking.googleapis.com"
  "vpcaccess.googleapis.com"
  "iam.googleapis.com"
  "compute.googleapis.com"
)

# Fetch currently enabled services once to avoid repeated API calls
ENABLED_SERVICES=$(gcloud services list --enabled \
  --project="${PROJECT_ID}" \
  --format="value(config.name)" 2>/dev/null || true)

TO_ENABLE=()
for api in "${REQUIRED_APIS[@]}"; do
  if echo "${ENABLED_SERVICES}" | grep -qx "${api}"; then
    echo "    [already enabled] ${api}"
  else
    TO_ENABLE+=("${api}")
  fi
done

if [[ ${#TO_ENABLE[@]} -gt 0 ]]; then
  echo "    Enabling: ${TO_ENABLE[*]}"
  gcloud services enable "${TO_ENABLE[@]}" --project="${PROJECT_ID}"
  echo "    APIs enabled."
else
  echo "    All APIs already enabled."
fi

# ── 4. Create Terraform state bucket ──────────────────────────────────────────
echo "==> [4/6] Creating Terraform state bucket: gs://${TFSTATE_BUCKET}..."

if gsutil ls -p "${PROJECT_ID}" "gs://${TFSTATE_BUCKET}" > /dev/null 2>&1; then
  echo "    Bucket already exists."
else
  gsutil mb \
    -p "${PROJECT_ID}" \
    -l EU \
    -b on \
    "gs://${TFSTATE_BUCKET}"

  # Enable versioning so state files are never permanently lost
  gsutil versioning set on "gs://${TFSTATE_BUCKET}"

  # Prevent public access
  gsutil pap set enforced "gs://${TFSTATE_BUCKET}"

  echo "    Bucket created with versioning and public access prevention."
fi

# ── 5. Write backend.tf ────────────────────────────────────────────────────────
echo "==> [5/6] Writing ${TF_BACKEND_FILE}..."

if [[ -f "${TF_BACKEND_FILE}" ]]; then
  echo "    ${TF_BACKEND_FILE} already exists — skipping."
  echo "    Contents:"
  cat "${TF_BACKEND_FILE}"
else
  mkdir -p "$(dirname "${TF_BACKEND_FILE}")"
  cat > "${TF_BACKEND_FILE}" <<TFEOF
# Auto-generated by ops/scripts/gcp-setup.sh — do not edit manually.
# To switch environments, update the prefix below.
terraform {
  backend "gcs" {
    bucket = "${TFSTATE_BUCKET}"
    prefix = "terraform/reflective"
  }
}
TFEOF
  echo "    Written."
  echo ""
  echo "    NOTE: versions.tf has a commented-out backend block — the auto-generated"
  echo "    backend.tf takes precedence. You can remove the comment from versions.tf"
  echo "    and delete backend.tf if you prefer to keep backend config in one file."
fi

# ── 6. Initialize Firebase ─────────────────────────────────────────────────────
echo "==> [6/6] Adding Firebase to project ${PROJECT_ID}..."

if firebase projects:list 2>/dev/null | grep -q "${PROJECT_ID}"; then
  echo "    Firebase already configured for ${PROJECT_ID}."
else
  if command -v firebase > /dev/null 2>&1; then
    firebase projects:addfirebase "${PROJECT_ID}" || \
      echo "    WARN: 'firebase projects:addfirebase' failed — Firebase may already be enabled."
  else
    echo "    WARN: firebase CLI not found. Install with: npm install -g firebase-tools"
    echo "    Then run: firebase projects:addfirebase ${PROJECT_ID}"
  fi
fi

# ── Done ───────────────────────────────────────────────────────────────────────
echo ""
echo "Bootstrap complete for project: ${PROJECT_ID}"
echo ""
echo "Next steps:"
echo "  1. just tf-init                    # initialize Terraform"
echo "  2. just tf-plan env=staging        # preview the plan"
echo "  3. just tf-apply env=staging       # apply to staging"
echo "  4. just firebase-deploy            # push Firestore/Storage rules"
